version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - xirorig_future
skip_non_tags: true
image: Visual Studio 2019
clone_depth: 1
init:
- pwsh: >-
    git config --global credential.helper store

    Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline

    git config --global user.email "${env:USER_EMAIL}"

    git config --global user.name "${env:USER_NAME}"
clone_script:
- pwsh: >-
    git clone -q --depth=1 --branch=${env.branch} https://github.com/TheDialgaTeam/Xirorig.git C:\projects\xirorig

    cd C:\projects\xirorig

    git checkout ${env.branch}

    git submodule update --init --recursive
dotnet_csproj:
  patch: true
  file: '**\Xirorig.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  access_token:
    secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
  USER_EMAIL:
    secure: bnLdl4lsS0uZ9SFoM9NBmgywfSlAl8W3GPoWSACdUXY=
  USER_NAME:
    secure: yqG96HTavsjSOHw/FNBQ+w==
  branch: xirorig_future
install:
- pwsh: >-
    # Initialize Cache because build time is too short to handle it

    Copy-Item "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows\*" -Destination "${env:LOCALAPPDATA}\vcpkg" -Force


    Copy-Item "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux\*" -Destination "C:\WSL\Ubuntu2004\rootfs\home\appveyor\.cache\vcpkg" -Force


    # Install latest .NET 6

    choco install dotnet-sdk --pre


    # Update and Install WSL toolchain

    wsl sudo apt-get update -y

    wsl sudo apt-get install curl zip unzip tar cmake ninja-build build-essential pkg-config gcc-10 gcc-10-arm-linux-gnueabihf gcc-10-aarch64-linux-gnu g++-10 g++-10-arm-linux-gnueabihf g++-10-aarch64-linux-gnu -y


    wsl sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10

    wsl sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 20


    wsl sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10

    wsl sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 20


    wsl sudo update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-10 20


    wsl sudo update-alternatives --install /usr/bin/arm-linux-gnueabihf-g++ arm-linux-gnueabihf-g++ /usr/bin/arm-linux-gnueabihf-g++-10 20


    wsl sudo update-alternatives --install /usr/bin/aarch64-linux-gnu-gcc aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-gnu-gcc-10 20


    wsl sudo update-alternatives --install /usr/bin/aarch64-linux-gnu-g++ aarch64-linux-gnu-g++ /usr/bin/aarch64-linux-gnu-g++-10 20
cache:
- '%LOCALAPPDATA%/vcpkg'
- C:/projects/xirorig/Xirorig.Native/xirorig_native/vcpkg/vcpkg
- C:/WSL/Ubuntu2004/rootfs/home/appveyor/.cache/vcpkg
build_script:
- pwsh: >-
    # Build Xirorig Native First

    $env:CHERE_INVOKING = 'yes'

    $env:MSYSTEM = 'MINGW64'

    C:\msys64\usr\bin\bash -lc "cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/c/projects/xirorig/Xirorig.Native/xirorig_native/out/install/x64-windows -DVCPKG_TARGET_TRIPLET=x64-mingw-static -S /c/projects/xirorig/Xirorig.Native/xirorig_native -B /c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x64-windows && ninja -C /c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x64-windows install"


    Copy-Item "${env:LOCALAPPDATA}\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    $env:MSYSTEM = 'MINGW32'

    C:\msys64\usr\bin\bash -lc "cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/c/projects/xirorig/Xirorig.Native/xirorig_native/out/install/x86-windows -DVCPKG_TARGET_TRIPLET=x86-mingw-static -S /c/projects/xirorig/Xirorig.Native/xirorig_native -B /c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x86-windows && ninja -C /c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x86-windows install"


    Copy-Item "${env:LOCALAPPDATA}\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    cmake -G "Visual Studio 16 2019" -A ARM -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/projects/xirorig/Xirorig.Native/xirorig_native/out/install/ARM32-windows -DVCPKG_TARGET_TRIPLET=arm-windows-static -DEXCLUDE_CPU_INFO_DEPENDENCY=true -S C:/projects/xirorig/Xirorig.Native/xirorig_native -B C:/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM32-windows


    cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsamd64_arm.bat" && msbuild.exe C:/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM32-windows/INSTALL.vcxproj'


    Copy-Item "${env:LOCALAPPDATA}\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    cmake -G "Visual Studio 16 2019" -A ARM64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/projects/xirorig/Xirorig.Native/xirorig_native/out/install/ARM64-windows -DVCPKG_TARGET_TRIPLET=arm64-windows-static -DEXCLUDE_CPU_INFO_DEPENDENCY=true -S C:/projects/xirorig/Xirorig.Native/xirorig_native -B C:/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM64-windows


    cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" && msbuild.exe C:/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM64-windows/INSTALL.vcxproj'


    Copy-Item "${env:LOCALAPPDATA}\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\windows\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    wsl cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/install/x64-linux" -DVCPKG_TARGET_TRIPLET=x64-linux -S "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native" -B "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x64-linux"

    wsl ninja -C "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/x64-linux" install


    Copy-Item "C:\WSL\Ubuntu2004\rootfs\home\appveyor\.cache\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    wsl cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/install/ARM32-linux" -DVCPKG_TARGET_TRIPLET=arm-linux -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/cmake/raspberrypi-arm.cmake" -S "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native" -B "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM32-linux"

    wsl ninja -C "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM32-linux" install


    Copy-Item "C:\WSL\Ubuntu2004\rootfs\home\appveyor\.cache\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    wsl cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/install/ARM64-linux" -DVCPKG_TARGET_TRIPLET=arm64-linux -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/cmake/raspberrypi-arm64.cmake" -S "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native" -B "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM64-linux"

    wsl ninja -C "/mnt/c/projects/xirorig/Xirorig.Native/xirorig_native/out/build/ARM64-linux" install


    Copy-Item "C:\WSL\Ubuntu2004\rootfs\home\appveyor\.cache\vcpkg\*" -Destination "C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux" -Force


    git add C:\projects\xirorig\Xirorig.Native\xirorig_native\vcpkg_cache\linux\*

    git commit -m "[ci skip] vcpkg cache update"

    git push -u origin ${env.branch}


    # Build Xirorig

    dotnet publish -p:PublishProfile=x64-windows.pubxml -p:Platform=x64 -c Release_windows


    dotnet publish -p:PublishProfile=x86-windows.pubxml -p:Platform=x86 -c Release_windows


    dotnet publish -p:PublishProfile=arm-windows.pubxml -p:Platform=ARM32 -c Release_windows


    dotnet publish -p:PublishProfile=arm64-windows.pubxml -p:Platform=ARM64 -c Release_windows


    dotnet publish -p:PublishProfile=x64-linux.pubxml -p:Platform=x64 -c Release_linux


    dotnet publish -p:PublishProfile=arm-linux.pubxml -p:Platform=ARM32 -c Release_linux


    dotnet publish -p:PublishProfile=arm64-linux.pubxml -p:Platform=ARM64 -c Release_linux


    dotnet publish -p:PublishProfile=x64-osx.pubxml -p:Platform=x64 -c Release_osx


    7z a Xirorig/publish/x64-windows.zip Xirorig/publish/x64-windows -mx=9

    7z a Xirorig/publish/x86-windows.zip Xirorig/publish/x86-windows -mx=9

    7z a Xirorig/publish/arm-windows.zip Xirorig/publish/arm-windows -mx=9

    7z a Xirorig/publish/arm64-windows.zip Xirorig/publish/arm64-windows -mx=9


    7z a Xirorig/publish/x64-linux.tar Xirorig/publish/x64-linux

    7z a Xirorig/publish/x64-linux.tar.gz Xirorig/publish/x64-linux.tar -mx=9


    7z a Xirorig/publish/arm-linux.tar Xirorig/publish/arm-linux

    7z a Xirorig/publish/arm-linux.tar.gz Xirorig/publish/arm-linux.tar -mx=9


    7z a Xirorig/publish/arm64-linux.tar Xirorig/publish/arm64-linux

    7z a Xirorig/publish/arm64-linux.tar.gz Xirorig/publish/arm64-linux.tar -mx=9


    7z a Xirorig/publish/x64-osx.tar Xirorig/publish/x64-osx

    7z a Xirorig/publish/x64-osx.tar.gz Xirorig/publish/x64-osx.tar -mx=9
test: off
artifacts:
- path: Xirorig/publish/x64-windows.zip
  name: x64-windows
- path: Xirorig/publish/x86-windows.zip
  name: x86-windows
- path: Xirorig/publish/arm-windows.zip
  name: arm-windows
- path: Xirorig/publish/arm64-windows.zip
  name: arm64-windows
- path: Xirorig/publish/x64-linux.tar.gz
  name: x64-linux
- path: Xirorig/publish/arm-linux.tar.gz
  name: arm-linux
- path: Xirorig/publish/arm64-linux.tar.gz
  name: arm64-linux
- path: Xirorig/publish/x64-osx.tar.gz
  name: x64-osx
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Xirorig v$(appveyor_build_version)
  auth_token:
    secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
  artifact: x64-windows, x86-windows, arm-windows, arm64-windows, x64-linux, arm-linux, arm64-linux, x64-osx
  draft: true
  prerelease: false