version: 1.0.0.{build}

branches:
  only:
  - xirorig_future

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

test: off

environment:
  APPVEYOR_TOKEN_KEY:
    secure: 4mjknPTlxavQwOJz2inXWUTSHXpsCB8Vjbt3nUuRAM8=

  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  DOTNET_VERSION: "6.0"
  DOTNET_RELEASE_STATUS: GA

  XIRORIG_NATIVE_ROOT: Xirorig.Native/xirorig_native
  XIRORIG_NATIVE_OUTPUT_ROOT: out
  XIRORIG_NATIVE_BUILD_ROOT: build
  XIRORIG_NATIVE_INSTALL_ROOT: install

  matrix:
  - job_name: Build Xirorig_Native Windows
    appveyor_build_worker_image: Visual Studio 2019
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_windows.zip

  - job_name: Build Xirorig_Native Linux
    appveyor_build_worker_image: Ubuntu2004
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_linux.zip

  - job_name: Build Xirorig_Native MacOS
    appveyor_build_worker_image: macos
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_osx.zip

  - job_name: Build Xirorig Windows
    job_depends_on: Build Xirorig_Native Windows
    appveyor_build_worker_image: Visual Studio 2019
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_windows.zip

  - job_name: Build Xirorig Linux
    job_depends_on: Build Xirorig_Native Linux
    appveyor_build_worker_image: Ubuntu2004
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_linux.zip

  - job_name: Build Xirorig MacOS
    job_depends_on: Build Xirorig_Native MacOS
    appveyor_build_worker_image: macos
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_osx.zip

matrix:
  fast_finish: true

clone_script:
- pwsh: appveyor/clone_script.ps1

install:
- pwsh: appveyor/install.ps1

build_script:
- pwsh: appveyor/build_script.ps1

for:
  -
    matrix:
      only:
        - job_name: Build Xirorig_Native Windows
    
    cache:
    - '%LOCALAPPDATA%/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg.exe'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_windows.zip
      name: Xirorig_Native_windows

  -
    matrix:
      only:
        - job_name: Build Xirorig_Native Linux

    cache:
    - '$HOME/.cache/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_linux.zip
      name: Xirorig_Native_linux

  -
    matrix:
      only:
        - job_name: Build Xirorig_Native MacOS

    cache:
    - '$HOME/.cache/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_osx.zip
      name: Xirorig_Native_osx

  -
    matrix:
      only:
        - job_name: Build Xirorig Windows

    dotnet_csproj:
      patch: true
      file: '**\Xirorig.csproj'
      version: '{version}'
      version_prefix: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    artifacts:
    - path: Xirorig/publish/x64-windows.zip
      name: x64-windows
    - path: Xirorig/publish/x86-windows.zip
      name: x86-windows
    - path: Xirorig/publish/arm-windows.zip
      name: arm-windows
    - path: Xirorig/publish/arm64-windows.zip
      name: arm64-windows

    deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: Xirorig v$(appveyor_build_version)
      auth_token:
        secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
      artifact: x64-windows, x86-windows, arm-windows, arm64-windows
      draft: true
      prerelease: false

  -
    matrix:
      only:
        - job_name: Build Xirorig Linux

    dotnet_csproj:
      patch: true
      file: '**\Xirorig.csproj'
      version: '{version}'
      version_prefix: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    artifacts:
    - path: Xirorig/publish/x64-linux.tar.gz
      name: x64-linux
    - path: Xirorig/publish/arm-linux.tar.gz
      name: arm-linux
    - path: Xirorig/publish/arm64-linux.tar.gz
      name: arm64-linux

    deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: Xirorig v$(appveyor_build_version)
      auth_token:
        secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
      artifact: x64-linux, arm-linux, arm64-linux
      draft: true
      prerelease: false

  -
    matrix:
      only:
        - job_name: Build Xirorig MacOS

    dotnet_csproj:
      patch: true
      file: '**\Xirorig.csproj'
      version: '{version}'
      version_prefix: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    artifacts:
    - path: Xirorig/publish/x64-osx.tar.gz
      name: x64-osx

    deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: Xirorig v$(appveyor_build_version)
      auth_token:
        secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
      artifact: x64-osx
      draft: true
      prerelease: false
