version: 1.0.0.{build}

branches:
  only:
  - xirorig_future

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

test: off

environment:
  APPVEYOR_TOKEN_KEY:
    secure: 4mjknPTlxavQwOJz2inXWUTSHXpsCB8Vjbt3nUuRAM8=

  DOTNET_VERSION: "6.0"
  DOTNET_RELEASE_STATUS: GA

  XIRORIG_ROOT: Xirorig
  XIRORIG_PUBLISH_ROOT: publish

  XIRORIG_NATIVE_ROOT: Xirorig.Native/xirorig_native
  XIRORIG_NATIVE_OUTPUT_ROOT: out
  XIRORIG_NATIVE_BUILD_ROOT: build
  XIRORIG_NATIVE_INSTALL_ROOT: install

  matrix:
  - job_name: Build Xirorig_Native Windows
    appveyor_build_worker_image: Visual Studio 2019
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_windows.zip

  - job_name: Build Xirorig_Native Linux
    appveyor_build_worker_image: Ubuntu2004
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_linux.zip

  - job_name: Build Xirorig_Native MacOS
    appveyor_build_worker_image: macos
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_osx.zip

  - job_name: Build Xirorig Windows
    job_group: Build Xirorig
    job_depends_on: Build Xirorig_Native Windows
    appveyor_build_worker_image: Visual Studio 2019
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_windows.zip

  - job_name: Build Xirorig Linux
    job_group: Build Xirorig
    job_depends_on: Build Xirorig_Native Linux
    appveyor_build_worker_image: Ubuntu2004
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_linux.zip

  - job_name: Build Xirorig MacOS
    job_group: Build Xirorig
    job_depends_on: Build Xirorig_Native MacOS
    appveyor_build_worker_image: macos
    XIRORIG_NATIVE_ARTIFACT_NAME: Xirorig_Native_osx.zip

  - job_name: Deploy Xirorig
    job_depends_on: Build Xirorig
    appveyor_build_worker_image: Visual Studio 2019

matrix:
  fast_finish: true

install:
- pwsh: appveyor/install.ps1

for:
  -
    matrix:
      exclude:
        - job_name: Deploy Xirorig
    
    clone_script:
    - pwsh: git clone -q --branch="${env:APPVEYOR_REPO_BRANCH}" "https://github.com/${env:APPVEYOR_REPO_NAME}.git" "${env:APPVEYOR_BUILD_FOLDER}"
    - pwsh: Set-Location "${env:APPVEYOR_BUILD_FOLDER}"
    - pwsh: git checkout -qf "${env:APPVEYOR_REPO_COMMIT}"
    - pwsh: git submodule -q update --init --recursive

    build_script:
    - pwsh: appveyor/build_script.ps1

  -
    matrix:
      only:
        - job_name: Build Xirorig_Native Windows
    
    cache:
    - '%LOCALAPPDATA%/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg.exe'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_windows.zip
      name: Xirorig_Native_windows

  -
    matrix:
      only:
        - job_name: Build Xirorig_Native Linux

    cache:
    - '$HOME/.cache/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_linux.zip
      name: Xirorig_Native_linux

  -
    matrix:
      only:
        - job_name: Build Xirorig_Native MacOS

    cache:
    - '$HOME/.cache/vcpkg'
    - '%APPVEYOR_BUILD_FOLDER%/%XIRORIG_NATIVE_ROOT%/vcpkg/vcpkg'

    artifacts:
    - path: Xirorig.Native/xirorig_native/out/install/Xirorig_Native_osx.zip
      name: Xirorig_Native_osx

  -
    matrix:
      only:
        - job_group: Build Xirorig

    dotnet_csproj:
      patch: true
      file: '**\Xirorig.csproj'
      version: '{version}'
      version_prefix: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

  -
    matrix:
      only:
        - job_name: Build Xirorig Windows

    artifacts:
    - path: Xirorig/publish/x64-windows.zip
      name: x64-windows
    - path: Xirorig/publish/x86-windows.zip
      name: x86-windows
    - path: Xirorig/publish/arm-windows.zip
      name: arm-windows
    - path: Xirorig/publish/arm64-windows.zip
      name: arm64-windows

  -
    matrix:
      only:
        - job_name: Build Xirorig Linux

    artifacts:
    - path: Xirorig/publish/x64-linux.tar.gz
      name: x64-linux
    - path: Xirorig/publish/arm-linux.tar.gz
      name: arm-linux
    - path: Xirorig/publish/arm64-linux.tar.gz
      name: arm64-linux

  -
    matrix:
      only:
        - job_name: Build Xirorig MacOS

    artifacts:
    - path: Xirorig/publish/x64-osx.tar.gz
      name: x64-osx

  -
    matrix:
      only:
        - job_name: Deploy Xirorig
    
    deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: Xirorig v$(appveyor_build_version)
      auth_token:
        secure: QwdWFtcb2ZSH9auLO0gQIhxsWRB88rHRvImJCrtJG/l/9bM2MCiVMGv0X4ivdFX3
      artifact: Xirorig/publish/*.zip, Xirorig/publish/*.tar.gz
      draft: true
      prerelease: false
