version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\TheDialgaTeam.Xiropht.Xirorig.Builder.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: >-
    git submodule update --init --recursive

    choco install dotnetcore-sdk --pre
build_script:
- cmd: >-
    cd Builder

    WIN_Build.bat
test: off
artifacts:
- path: bin/Release/mono-portable.zip
  name: mono-portable
- path: bin/Release/net-core-linux-arm.zip
  name: net-core-linux-arm
- path: bin/Release/net-core-linux-x64.zip
  name: net-core-linux-x64
- path: bin/Release/net-core-osx-x64.zip
  name: net-core-osx-x64
- path: bin/Release/net-core-win-arm.zip
  name: net-core-win-arm
- path: bin/Release/net-core-win-x64.zip
  name: net-core-win-x64
- path: bin/Release/net-core-win-x86.zip
  name: net-core-win-x86
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Xirorig v$(appveyor_build_version)
  auth_token:
    secure: N+JUPZbbAuyrCHxK+vor2jDWI0867mo0gqA5g0EWPwYgYZmAXztdRUV9rpwQ0TdR
  artifact: mono-portable, net-core-linux-arm, net-core-linux-x64, net-core-osx-x64, net-core-win-arm, net-core-win-x64, net-core-win-x86
  draft: true
  prerelease: false