/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The presets specify the generator and the build directory, and optionally a list of variables and other arguments to pass to CMake.
 */
export type Schema =
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 1;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV1;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 2;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV1;
      buildPresets?: BuildPresetsV2;
      testPresets?: TestPresetsV2;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 3;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV3;
      buildPresets?: BuildPresetsV3;
      testPresets?: TestPresetsV3;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 4;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV3;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV3;
      include?: Include;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 5;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV3;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV5;
      include?: Include;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 6;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV3;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV6;
      packagePresets?: PackagePresetsV6;
      workflowPresets?: WorkflowPresetsV6;
      include?: Include;
    }
  | {
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 7;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV7;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV6;
      packagePresets?: PackagePresetsV6;
      workflowPresets?: WorkflowPresetsV6;
      include?: Include;
    }
  | {
      $schema?: $Schema;
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 8;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV7;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV6;
      packagePresets?: PackagePresetsV6;
      workflowPresets?: WorkflowPresetsV6;
      include?: Include;
    }
  | {
      $schema?: $Schema;
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 9;
      cmakeMinimumRequired?: CmakeMinimumRequiredV1;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV7;
      buildPresets?: BuildPresetsV4;
      testPresets?: TestPresetsV6;
      packagePresets?: PackagePresetsV6;
      workflowPresets?: WorkflowPresetsV6;
      include?: Include;
    }
  | {
      $schema?: $Schema;
      $comment?: $Comment;
      /**
       * A required integer representing the version of the JSON schema.
       */
      version?: 10;
      cmakeMinimumRequired?: CmakeMinimumRequiredV10;
      vendor?: Vendor;
      configurePresets?: ConfigurePresetsV10;
      buildPresets?: BuildPresetsV10;
      testPresets?: TestPresetsV10;
      packagePresets?: PackagePresetsV10;
      workflowPresets?: WorkflowPresetsV10;
      include?: Include;
    };
/**
 * An optional object representing the minimum version of CMake needed to build this project. Available in version 1 and higher.
 */
export type CmakeMinimumRequiredV1 = CmakeMinimumRequiredPropertiesV1 & {
  major?: unknown;
  minor?: unknown;
  patch?: unknown;
};
/**
 * An optional array of configure preset objects. Available in version 1 and higher.
 */
export type ConfigurePresetsV1 = ConfigurePresetsItemsV1 & ConfigurePresetsV11;
/**
 * An optional array of configure preset objects. Available in version 1 and higher.
 */
export type ConfigurePresetsItemsV1 = {
  /**
   * A required string representing the machine-friendly name of the preset. This identifier is used in the --preset argument. There must not be two presets in the union of CMakePresets.json and CMakeUserPresets.json in the same directory with the same name.
   */
  name?: string;
  /**
   * An optional boolean specifying whether or not a preset should be hidden. If a preset is hidden, it cannot be used in the --preset= argument, will not show up in the CMake GUI, and does not have to have a valid generator or binaryDir, even from inheritance. Hidden presets are intended to be used as a base for other presets to inherit via the inherits field.
   */
  hidden?: boolean;
  inherits?: string | string[];
  /**
   * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, it should follow the same conventions as the root-level vendor field. If vendors use their own per-preset vendor field, they should implement inheritance in a sensible manner when appropriate.
   */
  vendor?: {
    [k: string]: unknown;
  };
  /**
   * An optional string with a human-friendly name of the preset.
   */
  displayName?: string;
  /**
   * An optional string with a human-friendly description of the preset.
   */
  description?: string;
  /**
   * An optional string representing the generator to use for the preset. If generator is not specified, it must be inherited from the inherits preset (unless this preset is hidden). Note that for Visual Studio generators, unlike in the command line -G argument, you cannot include the platform name in the generator name. Use the architecture field instead.
   */
  generator?: string;
  /**
   * An optional string representing the path to the output binary directory. This field supports macro expansion. If a relative path is specified, it is calculated relative to the source directory. If binaryDir is not specified, it must be inherited from the inherits preset (unless this preset is hidden).
   */
  binaryDir?: string;
  /**
   * An optional string representing the path to the CMake executable to use for this preset. This is reserved for use by IDEs, and is not used by CMake itself. IDEs that use this field should expand any macros in it.
   */
  cmakeExecutable?: string;
  /**
   * An optional map of cache variables. The key is the variable name (which must not be an empty string). Cache variables are inherited through the inherits field, and the preset's variables will be the union of its own cacheVariables and the cacheVariables from all its parents. If multiple presets in this union define the same variable, the standard rules of inherits are applied.
   */
  cacheVariables?: {
    [k: string]: unknown;
  };
  /**
   * An optional map of environment variables. The key is the variable name (which must not be an empty string). Each variable is set regardless of whether or not a value was given to it by the process's environment. This field supports macro expansion, and environment variables in this map may reference each other, and may be listed in any order, as long as such references do not cause a cycle (for example,if ENV_1 is $env{ENV_2}, ENV_2 may not be $env{ENV_1}.) Environment variables are inherited through the inherits field, and the preset's environment will be the union of its own environment and the environment from all its parents. If multiple presets in this union define the same variable, the standard rules of inherits are applied. Setting a variable to null causes it to not be set, even if a value was inherited from another preset.
   */
  environment?: {
    [k: string]: null | string;
  };
  /**
   * An optional object specifying warnings.
   */
  warnings?: {
    /**
     * An optional boolean. Equivalent to passing -Wdev or -Wno-dev on the command line. This may not be set to false if errors.dev is set to true.
     */
    dev?: boolean;
    /**
     * An optional boolean. Equivalent to passing -Wdeprecated or -Wno-deprecated on the command line. This may not be set to false if errors.deprecated is set to true.
     */
    deprecated?: boolean;
    /**
     * An optional boolean. Setting this to true is equivalent to passing --warn-uninitialized on the command line.
     */
    uninitialized?: boolean;
    /**
     * An optional boolean. Setting this to false is equivalent to passing --no-warn-unused-cli on the command line.
     */
    unusedCli?: boolean;
    /**
     * An optional boolean. Setting this to true is equivalent to passing --check-system-vars on the command line.
     */
    systemVars?: boolean;
    [k: string]: unknown;
  };
  /**
   * An optional object specifying errors.
   */
  errors?: {
    /**
     * An optional boolean. Equivalent to passing -Werror=dev or -Wno-error=dev on the command line. This may not be set to true if warnings.dev is set to false.
     */
    dev?: boolean;
    /**
     * An optional boolean. Equivalent to passing -Werror=deprecated or -Wno-error=deprecated on the command line. This may not be set to true if warnings.deprecated is set to false.
     */
    deprecated?: boolean;
    [k: string]: unknown;
  };
  /**
   * An optional object specifying debug options.
   */
  debug?: {
    /**
     * An optional boolean. Setting this to true is equivalent to passing --debug-output on the command line.
     */
    output?: boolean;
    /**
     * An optional boolean. Setting this to true is equivalent to passing --debug-trycompile on the command line.
     */
    tryCompile?: boolean;
    /**
     * An optional boolean. Setting this to true is equivalent to passing --debug-find on the command line.
     */
    find?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type ConfigurePresetsArchitectureV1 =
  | ConfigurePresetsArchitectureAsStringV1
  | ConfigurePresetsArchitectureAsObjectV1;
/**
 * An optional string representing the platform for generators that support it.
 */
export type ConfigurePresetsArchitectureAsStringV1 = string;
export type ConfigurePresetsToolsetV1 = ConfigurePresetsToolsetAsStringV1 | ConfigurePresetsToolsetAsObjectV1;
/**
 * An optional string representing the toolset for generators that support it.
 */
export type ConfigurePresetsToolsetAsStringV1 = string;
export type ConfigurePresetsCacheVariablesAdditionalPropertiesV1 =
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsNullV1
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsBooleanV1
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsStringV1
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsObjectV1;
/**
 * Setting a variable to null causes it to not be set, even if a value was inherited from another preset.
 */
export type ConfigurePresetsCacheVariablesAdditionalPropertiesAsNullV1 = null;
/**
 * A boolean representing the value of the variable. Equivalent to "TRUE" or "FALSE".
 */
export type ConfigurePresetsCacheVariablesAdditionalPropertiesAsBooleanV1 = boolean;
/**
 * A string representing the value of the variable (which supports macro expansion).
 */
export type ConfigurePresetsCacheVariablesAdditionalPropertiesAsStringV1 = string;
export type ConfigurePresetsV11 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  generator?: unknown;
  architecture?: ConfigurePresetsArchitectureV1;
  toolset?: ConfigurePresetsToolsetV1;
  binaryDir?: unknown;
  cmakeExecutable?: unknown;
  cacheVariables?: {
    [k: string]: ConfigurePresetsCacheVariablesAdditionalPropertiesV1;
  };
  environment?: unknown;
  warnings?: {
    dev?: unknown;
    deprecated?: unknown;
    uninitialized?: unknown;
    unusedCli?: unknown;
    systemVars?: unknown;
  };
  errors?: {
    dev?: unknown;
    deprecated?: unknown;
  };
  debug?: {
    output?: unknown;
    tryCompile?: unknown;
    find?: unknown;
  };
}[];
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 2 and higher.
 */
export type BuildPresetsV2 = BuildPresetsItemsV2 & BuildPresetsV21;
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 2 and higher.
 */
export type BuildPresetsItemsV2 = {
  /**
   * A required string representing the machine-friendly name of the preset. This identifier is used in the --preset argument. There must not be two presets (configure, build, test, package, or workflow) in the union of CMakePresets.json and CMakeUserPresets.json in the same directory with the same name.
   */
  name?: string;
  /**
   * An optional boolean specifying whether or not a preset should be hidden. If a preset is hidden, it cannot be used in the --preset argument and does not have to have a valid configurePreset, even from inheritance. Hidden presets are intended to be used as a base for other presets to inherit via the inherits field.
   */
  hidden?: boolean;
  inherits?: string | string[];
  /**
   * An optional string specifying the name of a configure preset to associate with this build preset. If configurePreset is not specified, it must be inherited from the inherits preset (unless this preset is hidden). The build tree directory is inferred from the configure preset.
   */
  configurePreset?: string;
  /**
   * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, it should follow the same conventions as the root-level vendor field. If vendors use their own per-preset vendor field, they should implement inheritance in a sensible manner when appropriate.
   */
  vendor?: {
    [k: string]: unknown;
  };
  /**
   * An optional string with a human-friendly name of the preset.
   */
  displayName?: string;
  /**
   * An optional string with a human-friendly description of the preset.
   */
  description?: string;
  /**
   * An optional boolean that defaults to true. If true, the environment variables from the associated configure preset are inherited after all inherited build preset environments, but before environment variables explicitly specified in this build preset.
   */
  inheritConfigureEnvironment?: boolean;
  /**
   * An optional map of environment variables. The key is the variable name (which must not be an empty string). Each variable is set regardless of whether or not a value was given to it by the process's environment. This field supports macro expansion, and environment variables in this map may reference each other, and may be listed in any order, as long as such references do not cause a cycle (for example,if ENV_1 is $env{ENV_2}, ENV_2 may not be $env{ENV_1}.) Environment variables are inherited through the inherits field, and the preset's environment will be the union of its own environment and the environment from all its parents. If multiple presets in this union define the same variable, the standard rules of inherits are applied. Setting a variable to null causes it to not be set, even if a value was inherited from another preset.
   */
  environment?: {
    [k: string]: null | string;
  };
  /**
   * An optional integer. Equivalent to passing --parallel or -j on the command line.
   */
  jobs?: number;
  targets?: string | string[];
  /**
   * An optional string. Equivalent to passing --config on the command line.
   */
  configuration?: string;
  /**
   * An optional boolean. If true, equivalent to passing --clean-first on the command line.
   */
  cleanFirst?: boolean;
  /**
   * An optional boolean. If true, equivalent to passing --verbose on the command line.
   */
  verbose?: boolean;
  /**
   * An optional array of strings. Equivalent to passing options after -- on the command line.
   */
  nativeToolOptions?: string[];
  [k: string]: unknown;
}[];
export type BuildPresetsV21 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  jobs?: unknown;
  targets?: unknown;
  configuration?: unknown;
  cleanFirst?: unknown;
  verbose?: unknown;
  nativeToolOptions?: unknown;
}[];
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 2 and higher.
 */
export type TestPresetsV2 = TestPresetsItemsV2 & TestPresetsV21;
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 2 and higher.
 */
export type TestPresetsItemsV2 = {
  /**
   * A required string representing the machine-friendly name of the preset. This identifier is used in the --preset argument. There must not be two presets (configure, build, test, package, or workflow) in the union of CMakePresets.json and CMakeUserPresets.json in the same directory with the same name.
   */
  name?: string;
  /**
   * An optional boolean specifying whether or not a preset should be hidden. If a preset is hidden, it cannot be used in the --preset argument and does not have to have a valid configurePreset, even from inheritance. Hidden presets are intended to be used as a base for other presets to inherit via the inherits field.
   */
  hidden?: boolean;
  inherits?: string | string[];
  /**
   * An optional string specifying the name of a configure preset to associate with this test preset. If configurePreset is not specified, it must be inherited from the inherits preset (unless this preset is hidden). The build tree directory is inferred from the configure preset.
   */
  configurePreset?: string;
  /**
   * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, it should follow the same conventions as the root-level vendor field. If vendors use their own per-preset vendor field, they should implement inheritance in a sensible manner when appropriate.
   */
  vendor?: {
    [k: string]: unknown;
  };
  /**
   * An optional string with a human-friendly name of the preset.
   */
  displayName?: string;
  /**
   * An optional string with a human-friendly description of the preset.
   */
  description?: string;
  /**
   * An optional boolean that defaults to true. If true, the environment variables from the associated configure preset are inherited after all inherited test preset environments, but before environment variables explicitly specified in this test preset.
   */
  inheritConfigureEnvironment?: boolean;
  /**
   * An optional map of environment variables. The key is the variable name (which must not be an empty string). Each variable is set regardless of whether or not a value was given to it by the process's environment. This field supports macro expansion, and environment variables in this map may reference each other, and may be listed in any order, as long as such references do not cause a cycle (for example,if ENV_1 is $env{ENV_2}, ENV_2 may not be $env{ENV_1}.) Environment variables are inherited through the inherits field, and the preset's environment will be the union of its own environment and the environment from all its parents. If multiple presets in this union define the same variable, the standard rules of inherits are applied. Setting a variable to null causes it to not be set, even if a value was inherited from another preset.
   */
  environment?: {
    [k: string]: null | string;
  };
  /**
   * An optional string. Equivalent to passing --build-config on the command line.
   */
  configuration?: string;
  /**
   * An optional array of configuration options to overwrite options specified in the CTest configuration file. Equivalent to passing ``--overwrite`` for each value in the array.
   */
  overwriteConfigurationFile?: string[];
  /**
   * An optional object specifying output options.
   */
  output?: {
    /**
     * An optional boolean. If true, equivalent to passing --progress on the command line.
     */
    shortProgress?: boolean;
    /**
     * An optional string specifying verbosity level. Valid values are "default" (equivalent to passing no verbosity flags on the command line), "verbose" (equivalent to passing --verbose on the command line), and "extra" (equivalent to passing --extra-verbose on the command line).
     */
    verbosity?: "default" | "verbose" | "extra";
    /**
     * An optional boolean. If true, equivalent to passing --debug on the command line.
     */
    debug?: boolean;
    /**
     * An optional boolean. If true, equivalent to passing --output-on-failure on the command line.
     */
    outputOnFailure?: boolean;
    /**
     * An optional boolean. If true, equivalent to passing --quiet on the command line.
     */
    quiet?: boolean;
    /**
     * An optional string specifying a path to a log file. Equivalent to passing --output-log on the command line.
     */
    outputLogFile?: string;
    /**
     * An optional boolean. If false, equivalent to passing --no-label-summary on the command line.
     */
    labelSummary?: boolean;
    /**
     * An optional boolean. If false, equivalent to passing --no-subproject-summary on the command line.
     */
    subprojectSummary?: boolean;
    /**
     * An optional integer specifying the maximum output for passed tests in bytes. Equivalent to passing --test-output-size-passed on the command line.
     */
    maxPassedTestOutputSize?: number;
    /**
     * An optional integer specifying the maximum output for failed tests in bytes. Equivalent to passing --test-output-size-failed on the command line.
     */
    maxFailedTestOutputSize?: number;
    /**
     * An optional integer specifying the maximum width of a test name to output. Equivalent to passing --max-width on the command line.
     */
    maxTestNameWidth?: number;
    [k: string]: unknown;
  };
  /**
   * An optional object specifying how to filter the tests to run.
   */
  filter?: {
    /**
     * An optional object specifying which tests to include.
     */
    include?: {
      /**
       * An optional string specifying a regex for test names. Equivalent to passing --tests-regex on the command line.
       */
      name?: string;
      /**
       * An optional string specifying a regex for test labels. Equivalent to passing --label-regex on the command line.
       */
      label?: string;
      /**
       * An optional boolean. Equivalent to passing --union on the command line.
       */
      useUnion?: boolean;
      [k: string]: unknown;
    };
    /**
     * An optional object specifying which tests to exclude.
     */
    exclude?: {
      /**
       * An optional string specifying a regex for test names. Equivalent to passing --exclude-regex on the command line.
       */
      name?: string;
      /**
       * An optional string specifying a regex for test labels. Equivalent to passing --label-exclude on the command line.
       */
      label?: string;
      /**
       * An optional object specifying which fixtures to exclude from adding tests.
       */
      fixtures?: {
        /**
         * An optional string specifying a regex for text fixtures to exclude from adding any tests. Equivalent to --fixture-exclude-any on the command line.
         */
        any?: string;
        /**
         * An optional string specifying a regex for text fixtures to exclude from adding setup tests. Equivalent to --fixture-exclude-setup on the command line.
         */
        setup?: string;
        /**
         * An optional string specifying a regex for text fixtures to exclude from adding cleanup tests. Equivalent to --fixture-exclude-cleanup on the command line.
         */
        cleanup?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * An optional object specifying options for test execution.
   */
  execution?: {
    /**
     * An optional boolean. If true, equivalent to passing --stop-on-failure on the command line.
     */
    stopOnFailure?: boolean;
    /**
     * An optional boolean. If true, equivalent to passing -F on the command line.
     */
    enableFailover?: boolean;
    /**
     * An optional integer. Equivalent to passing --parallel on the command line.
     */
    jobs?: number;
    /**
     * An optional string. Equivalent to passing --resource-spec-file on the command line.
     */
    resourceSpecFile?: string;
    /**
     * An optional integer. Equivalent to passing --test-load on the command line.
     */
    testLoad?: number;
    /**
     * An optional string. Equivalent to passing --show-only on the command line. Value must be "human" or "json-v1".
     */
    showOnly?: "human" | "json-v1";
    /**
     * An optional object specifying how to repeat tests. Equivalent to passing --repeat on the command line.
     */
    repeat?: {
      /**
       * A required string. Must be one of the following values: "until-fail", "until-pass", or "after-timeout".
       */
      mode?: "until-fail" | "until-pass" | "after-timeout";
      /**
       * A required integer.
       */
      count?: number;
      [k: string]: unknown;
    };
    /**
     * An optional boolean. If true, equivalent to passing --interactive-debug-mode 1 on the command line. If false, equivalent to passing --interactive-debug-mode 0 on the command line.
     */
    interactiveDebugging?: boolean;
    /**
     * An optional boolean. If true, equivalent to passing --schedule-random on the command line.
     */
    scheduleRandom?: boolean;
    /**
     * An optional integer. Equivalent to passing --timeout on the command line.
     */
    timeout?: number;
    /**
     * An optional string specifying the behavior if no tests are found. Must be one of the following values: "default" (equivalent to not passing any value on the command line), "error" (equivalent to passing --no-tests=error on the command line), or "ignore" (equivalent to passing --no-tests-ignore on the command line).
     */
    noTestsAction?: "default" | "error" | "ignore";
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type TestPresetsFilterIncludeIndexV2 =
  | TestPresetsFilterIncludeIndexAsStringV2
  | TestPresetsFilterIncludeIndexAsObjectV2;
/**
 * An optional string specifying a file with the command line syntax for --tests-information. Available in version 2 and higher.
 */
export type TestPresetsFilterIncludeIndexAsStringV2 = string;
export type TestPresetsV21 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  configuration?: unknown;
  overwriteConfigurationFile?: unknown;
  output?: {
    shortProgress?: unknown;
    verbosity?: unknown;
    debug?: unknown;
    outputOnFailure?: unknown;
    quiet?: unknown;
    outputLogFile?: unknown;
    labelSummary?: unknown;
    subprojectSummary?: unknown;
    maxPassedTestOutputSize?: unknown;
    maxFailedTestOutputSize?: unknown;
    maxTestNameWidth?: unknown;
  };
  filter?: {
    include?: {
      name?: unknown;
      label?: unknown;
      useUnion?: unknown;
      index?: TestPresetsFilterIncludeIndexV2;
    };
    exclude?: {
      name?: unknown;
      label?: unknown;
      fixtures?: {
        any?: unknown;
        setup?: unknown;
        cleanup?: unknown;
      };
    };
  };
  execution?: {
    stopOnFailure?: unknown;
    enableFailover?: unknown;
    jobs?: unknown;
    resourceSpecFile?: unknown;
    testLoad?: unknown;
    showOnly?: unknown;
    repeat?: {
      mode: unknown;
      count: unknown;
    };
    interactiveDebugging?: unknown;
    scheduleRandom?: unknown;
    timeout?: unknown;
    noTestsAction?: unknown;
  };
}[];
/**
 * An optional array of configure preset objects. Available in version 3 and higher.
 */
export type ConfigurePresetsV3 = ConfigurePresetsItemsV3 & ConfigurePresetsItemsV1 & ConfigurePresetsV31;
/**
 * An optional array of configure preset objects. Available in version 3 and higher.
 */
export type ConfigurePresetsItemsV3 = {
  /**
   * An optional string representing the path to the output binary directory. This field supports macro expansion. If a relative path is specified, it is calculated relative to the source directory. If binaryDir is not specified, the path is calculated using regular methods.
   */
  binaryDir?: string;
  /**
   * An optional string representing the generator to use for the preset. If generator is not specified, the normal generator discovery procedure is used. Note that for Visual Studio generators, unlike in the command line -G argument, you cannot include the platform name in the generator name. Use the architecture field instead.
   */
  generator?: string;
  /**
   * An optional string representing the path to the toolchain file. This field supports macro expansion. If a relative path is specified, it is calculated relative to the build directory, and if not found, relative to the source directory.
   */
  toolchainFile?: string;
  /**
   * An optional string representing the path to the installation directory. This field supports macro expansion. If a relative path is specified, it is calculated relative to the source directory.
   */
  installDir?: string;
  [k: string]: unknown;
}[];
export type TopConditionV3 = ConditionV3 | TopConditionAsNullV3;
export type ConditionV3 =
  | ConditionAsBooleanV3
  | ConditionAsObjectConstV3
  | ConditionAsObjectEqualsV3
  | ConditionAsObjectInListV3
  | ConditionAsObjectMatchesV3
  | ConditionAsObjectAggregationV3
  | ConditionAsObjectNotV3;
/**
 * A boolean which provides a constant value for the condition's evaluation.
 */
export type ConditionAsBooleanV3 = boolean;
/**
 * Null indicates that the condition always evaluates to true and is not inherited.
 */
export type TopConditionAsNullV3 = null;
export type ConfigurePresetsV31 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  generator?: unknown;
  architecture?: ConfigurePresetsArchitectureV1;
  toolset?: ConfigurePresetsToolsetV1;
  toolchainFile?: unknown;
  binaryDir?: unknown;
  installDir?: unknown;
  cmakeExecutable?: unknown;
  cacheVariables?: {
    [k: string]: ConfigurePresetsCacheVariablesAdditionalPropertiesV1;
  };
  environment?: unknown;
  warnings?: {
    dev?: unknown;
    deprecated?: unknown;
    uninitialized?: unknown;
    unusedCli?: unknown;
    systemVars?: unknown;
  };
  errors?: {
    dev?: unknown;
    deprecated?: unknown;
  };
  debug?: {
    output?: unknown;
    tryCompile?: unknown;
    find?: unknown;
  };
  condition?: TopConditionV3;
}[];
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 3 and higher.
 */
export type BuildPresetsV3 = BuildPresetsItemsV3 & BuildPresetsItemsV2 & BuildPresetsV31;
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 3 and higher.
 */
export type BuildPresetsItemsV3 = unknown[];
export type BuildPresetsV31 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  jobs?: unknown;
  targets?: unknown;
  configuration?: unknown;
  cleanFirst?: unknown;
  verbose?: unknown;
  nativeToolOptions?: unknown;
  condition?: TopConditionV3;
}[];
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 3 and higher.
 */
export type TestPresetsV3 = TestPresetsItemsV3 & TestPresetsItemsV2 & TestPresetsV31;
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 3 and higher.
 */
export type TestPresetsItemsV3 = unknown[];
export type TestPresetsV31 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  configuration?: unknown;
  overwriteConfigurationFile?: unknown;
  output?: {
    shortProgress?: unknown;
    verbosity?: unknown;
    debug?: unknown;
    outputOnFailure?: unknown;
    quiet?: unknown;
    outputLogFile?: unknown;
    labelSummary?: unknown;
    subprojectSummary?: unknown;
    maxPassedTestOutputSize?: unknown;
    maxFailedTestOutputSize?: unknown;
    maxTestNameWidth?: unknown;
  };
  filter?: {
    include?: {
      name?: unknown;
      label?: unknown;
      useUnion?: unknown;
      index?: TestPresetsFilterIncludeIndexV2;
    };
    exclude?: {
      name?: unknown;
      label?: unknown;
      fixtures?: {
        any?: unknown;
        setup?: unknown;
        cleanup?: unknown;
      };
    };
  };
  execution?: {
    stopOnFailure?: unknown;
    enableFailover?: unknown;
    jobs?: unknown;
    resourceSpecFile?: unknown;
    testLoad?: unknown;
    showOnly?: unknown;
    repeat?: {
      mode: unknown;
      count: unknown;
    };
    interactiveDebugging?: unknown;
    scheduleRandom?: unknown;
    timeout?: unknown;
    noTestsAction?: unknown;
  };
  condition?: TopConditionV3;
}[];
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 4 and higher.
 */
export type BuildPresetsV4 = BuildPresetsItemsV4 & BuildPresetsItemsV3 & BuildPresetsItemsV2 & BuildPresetsV41;
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 4 and higher.
 */
export type BuildPresetsItemsV4 = {
  /**
   * An optional string specifying the package resolve behavior. Valid values are "on" (packages are resolved prior to the build), "off" (packages are not resolved prior to the build), and "only" (packages are resolved, but no build will be performed).
   */
  resolvePackageReferences?: "on" | "off" | "only";
  [k: string]: unknown;
}[];
export type BuildPresetsV41 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  jobs?: unknown;
  targets?: unknown;
  configuration?: unknown;
  cleanFirst?: unknown;
  resolvePackageReferences?: unknown;
  verbose?: unknown;
  nativeToolOptions?: unknown;
  condition?: TopConditionV3;
}[];
/**
 * An optional array of strings representing files to include. If the filenames are not absolute, they are considered relative to the current file.
 */
export type Include = string[];
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 5 and higher.
 */
export type TestPresetsV5 = TestPresetsItemsV5 & TestPresetsItemsV3 & TestPresetsItemsV2 & TestPresetsV51;
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 5 and higher.
 */
export type TestPresetsItemsV5 = {
  /**
   * An optional object specifying output options.
   */
  output?: {
    /**
     * An optional string specifying the test output truncation mode. Equivalent to passing --test-output-truncation on the command line. Must be one of the following values: "tail", "middle", or "head".
     */
    testOutputTruncation?: "tail" | "middle" | "head";
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type TestPresetsV51 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  configuration?: unknown;
  overwriteConfigurationFile?: unknown;
  output?: {
    shortProgress?: unknown;
    verbosity?: unknown;
    debug?: unknown;
    outputOnFailure?: unknown;
    quiet?: unknown;
    outputLogFile?: unknown;
    labelSummary?: unknown;
    subprojectSummary?: unknown;
    maxPassedTestOutputSize?: unknown;
    maxFailedTestOutputSize?: unknown;
    maxTestNameWidth?: unknown;
    testOutputTruncation?: unknown;
  };
  filter?: {
    include?: {
      name?: unknown;
      label?: unknown;
      useUnion?: unknown;
      index?: TestPresetsFilterIncludeIndexV2;
    };
    exclude?: {
      name?: unknown;
      label?: unknown;
      fixtures?: {
        any?: unknown;
        setup?: unknown;
        cleanup?: unknown;
      };
    };
  };
  execution?: {
    stopOnFailure?: unknown;
    enableFailover?: unknown;
    jobs?: unknown;
    resourceSpecFile?: unknown;
    testLoad?: unknown;
    showOnly?: unknown;
    repeat?: {
      mode: unknown;
      count: unknown;
    };
    interactiveDebugging?: unknown;
    scheduleRandom?: unknown;
    timeout?: unknown;
    noTestsAction?: unknown;
  };
  condition?: TopConditionV3;
}[];
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 6 and higher.
 */
export type TestPresetsV6 = TestPresetsItemsV6 &
  TestPresetsItemsV5 &
  TestPresetsItemsV3 &
  TestPresetsItemsV2 &
  TestPresetsV61;
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 6 and higher.
 */
export type TestPresetsItemsV6 = {
  /**
   * An optional object specifying output options.
   */
  output?: {
    /**
     * An optional string specifying a path to a JUnit file. Equivalent to passing --output-junit on the command line.
     */
    outputJUnitFile?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type TestPresetsV61 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  configuration?: unknown;
  overwriteConfigurationFile?: unknown;
  output?: {
    shortProgress?: unknown;
    verbosity?: unknown;
    debug?: unknown;
    outputOnFailure?: unknown;
    quiet?: unknown;
    outputLogFile?: unknown;
    outputJUnitFile?: unknown;
    labelSummary?: unknown;
    subprojectSummary?: unknown;
    maxPassedTestOutputSize?: unknown;
    maxFailedTestOutputSize?: unknown;
    maxTestNameWidth?: unknown;
    testOutputTruncation?: unknown;
  };
  filter?: {
    include?: {
      name?: unknown;
      label?: unknown;
      useUnion?: unknown;
      index?: TestPresetsFilterIncludeIndexV2;
    };
    exclude?: {
      name?: unknown;
      label?: unknown;
      fixtures?: {
        any?: unknown;
        setup?: unknown;
        cleanup?: unknown;
      };
    };
  };
  execution?: {
    stopOnFailure?: unknown;
    enableFailover?: unknown;
    jobs?: unknown;
    resourceSpecFile?: unknown;
    testLoad?: unknown;
    showOnly?: unknown;
    repeat?: {
      mode: unknown;
      count: unknown;
    };
    interactiveDebugging?: unknown;
    scheduleRandom?: unknown;
    timeout?: unknown;
    noTestsAction?: unknown;
  };
  condition?: TopConditionV3;
}[];
/**
 * An optional array of package preset objects. Used to specify arguments to cpack. Available in version 6 and higher.
 */
export type PackagePresetsV6 = PackagePresetsItemsV6 & PackagePresetsV61;
/**
 * An optional array of package preset objects. Used to specify arguments to cpack. Available in version 6 and higher.
 */
export type PackagePresetsItemsV6 = {
  /**
   * A required string representing the machine-friendly name of the preset. This identifier is used in the --preset argument. There must not be two presets (configure, build, test, package, or workflow) in the union of CMakePresets.json and CMakeUserPresets.json in the same directory with the same name.
   */
  name?: string;
  /**
   * An optional boolean specifying whether or not a preset should be hidden. If a preset is hidden, it cannot be used in the --preset argument and does not have to have a valid configurePreset, even from inheritance. Hidden presets are intended to be used as a base for other presets to inherit via the inherits field.
   */
  hidden?: boolean;
  inherits?: string | string[];
  /**
   * An optional string specifying the name of a configure preset to associate with this package preset. If configurePreset is not specified, it must be inherited from the inherits preset (unless this preset is hidden). The build tree directory is inferred from the configure preset.
   */
  configurePreset?: string;
  /**
   * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, it should follow the same conventions as the root-level vendor field. If vendors use their own per-preset vendor field, they should implement inheritance in a sensible manner when appropriate.
   */
  vendor?: {
    [k: string]: unknown;
  };
  /**
   * An optional string with a human-friendly name of the preset.
   */
  displayName?: string;
  /**
   * An optional string with a human-friendly description of the preset.
   */
  description?: string;
  /**
   * An optional boolean that defaults to true. If true, the environment variables from the associated configure preset are inherited after all inherited package preset environments, but before environment variables explicitly specified in this package preset.
   */
  inheritConfigureEnvironment?: boolean;
  /**
   * An optional map of environment variables. The key is the variable name (which must not be an empty string). Each variable is set regardless of whether or not a value was given to it by the process's environment. This field supports macro expansion, and environment variables in this map may reference each other, and may be listed in any order, as long as such references do not cause a cycle (for example,if ENV_1 is $env{ENV_2}, ENV_2 may not be $env{ENV_1}.) Environment variables are inherited through the inherits field, and the preset's environment will be the union of its own environment and the environment from all its parents. If multiple presets in this union define the same variable, the standard rules of inherits are applied. Setting a variable to null causes it to not be set, even if a value was inherited from another preset.
   */
  environment?: {
    [k: string]: null | string;
  };
  /**
   * An optional list of strings representing generators for CPack to use.
   */
  generators?: string[];
  /**
   * An optional list of strings representing build configurations for CPack to package.
   */
  configurations?: string[];
  /**
   * An optional map of variables to pass to CPack, equivalent to -D arguments. Each key is the name of a variable, and the value is the string to assign to that variable.
   */
  variables?: {
    [k: string]: unknown;
  };
  /**
   * An optional string representing the config file for CPack to use.
   */
  configFile?: string;
  /**
   * An optional object specifying output options.
   */
  output?: {
    /**
     * An optional boolean specifying whether or not to print debug information. A value of true is equivalent to passing --debug on the command line.
     */
    debug?: boolean;
    /**
     * An optional boolean specifying whether or not to print verbosely. A value of true is equivalent to passing --verbose on the command line.
     */
    verbose?: boolean;
    [k: string]: unknown;
  };
  /**
   * An optional string representing the package name.
   */
  packageName?: string;
  /**
   * An optional string representing the package version.
   */
  packageVersion?: string;
  /**
   * An optional string representing the directory in which to place the package.
   */
  packageDirectory?: string;
  /**
   * An optional string representing the vendor name.
   */
  vendorName?: string;
  [k: string]: unknown;
}[];
export type PackagePresetsV61 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  condition?: TopConditionV3;
  generators?: unknown;
  configurations?: unknown;
  variables?: unknown;
  configFile?: unknown;
  output?: {
    debug?: unknown;
    verbose?: unknown;
  };
  packageName?: unknown;
  packageVersion?: unknown;
  packageDirectory?: unknown;
  vendorName?: unknown;
}[];
/**
 * An optional array of workflow preset objects. Used to execute configure, build, test, and package presets in order. Available in version 6 and higher.
 */
export type WorkflowPresetsV6 = WorkflowPresetsItemsV6 & WorkflowPresetsV61;
/**
 * An optional array of workflow preset objects. Used to execute configure, build, test, and package presets in order. Available in version 6 and higher.
 */
export type WorkflowPresetsItemsV6 = {
  /**
   * A required string representing the machine-friendly name of the preset. This identifier is used in the --preset argument. There must not be two presets (configure, build, test, package, or workflow) in the union of CMakePresets.json and CMakeUserPresets.json in the same directory with the same name.
   */
  name?: string;
  /**
   * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, it should follow the same conventions as the root-level vendor field.
   */
  vendor?: {
    [k: string]: unknown;
  };
  /**
   * An optional string with a human-friendly name of the preset.
   */
  displayName?: string;
  /**
   * An optional string with a human-friendly description of the preset.
   */
  description?: string;
  /**
   * A required array of objects describing the steps of the workflow. The first step must be a configure preset, and all subsequent steps must be non-configure presets whose configurePreset field matches the starting configure preset.
   */
  steps?: {
    /**
     * A required string. The first step must be configure. Subsequent steps must be either build, test, or package.
     */
    type?: "configure" | "build" | "test" | "package";
    /**
     * A required string representing the name of the configure, build, test, or package preset to run as this workflow step.
     */
    name?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}[];
export type WorkflowPresetsV61 = {
  name: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  steps: {
    type: unknown;
    name: unknown;
  }[];
}[];
/**
 * An optional array of configure preset objects. Available in version 7 and higher.
 */
export type ConfigurePresetsV7 = ConfigurePresetsItemsV7 &
  ConfigurePresetsItemsV3 &
  ConfigurePresetsItemsV1 &
  ConfigurePresetsV71;
/**
 * An optional array of configure preset objects. Available in version 7 and higher.
 */
export type ConfigurePresetsItemsV7 = {
  /**
   * An optional object specifying trace options.
   */
  trace?: {
    /**
     * An optional string that specifies the trace mode.
     */
    mode?: "on" | "off" | "expand";
    /**
     * An optional string that specifies the trace output format.
     */
    format?: "human" | "json-v1";
    source?: string | string[];
    /**
     * An optional string specifying a path to a trace output file.
     */
    redirect?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type ConfigurePresetsV71 = {
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  generator?: unknown;
  architecture?: ConfigurePresetsArchitectureV1;
  toolset?: ConfigurePresetsToolsetV1;
  toolchainFile?: unknown;
  binaryDir?: unknown;
  installDir?: unknown;
  cmakeExecutable?: unknown;
  cacheVariables?: {
    [k: string]: ConfigurePresetsCacheVariablesAdditionalPropertiesV1;
  };
  environment?: unknown;
  warnings?: {
    dev?: unknown;
    deprecated?: unknown;
    uninitialized?: unknown;
    unusedCli?: unknown;
    systemVars?: unknown;
  };
  errors?: {
    dev?: unknown;
    deprecated?: unknown;
  };
  debug?: {
    output?: unknown;
    tryCompile?: unknown;
    find?: unknown;
  };
  condition?: TopConditionV3;
  trace?: {
    mode?: unknown;
    format?: unknown;
    source?: unknown;
    redirect?: unknown;
  };
}[];
/**
 * The schema against which to verify this document.
 */
export type $Schema = string;
export type $Comment = string | [string, ...string[]];
/**
 * An optional object representing the minimum version of CMake needed to build this project. Available in version 10 and higher.
 */
export type CmakeMinimumRequiredV10 = CmakeMinimumRequiredPropertiesV10 &
  CmakeMinimumRequiredPropertiesV1 & {
    $comment?: unknown;
    major?: unknown;
    minor?: unknown;
    patch?: unknown;
  };
/**
 * An optional array of configure preset objects. Available in version 10 and higher.
 */
export type ConfigurePresetsV10 = ConfigurePresetsItemsV10 &
  ConfigurePresetsItemsV7 &
  ConfigurePresetsItemsV3 &
  ConfigurePresetsItemsV1 &
  ConfigurePresetsV101;
/**
 * An optional array of configure preset objects. Available in version 10 and higher.
 */
export type ConfigurePresetsItemsV10 = {
  $comment?: $Comment;
  warnings?: {
    $comment?: $Comment;
    [k: string]: unknown;
  };
  errors?: {
    $comment?: $Comment;
    [k: string]: unknown;
  };
  debug?: {
    $comment?: $Comment;
    [k: string]: unknown;
  };
  trace?: {
    $comment?: $Comment;
    [k: string]: unknown;
  };
  /**
   * An optional string specifying the path to graphviz dot file. Available in version 10 and higher.
   */
  graphviz?: string;
  [k: string]: unknown;
}[];
export type ConfigurePresetsArchitectureV10 =
  | ConfigurePresetsArchitectureAsStringV1
  | (ConfigurePresetsArchitectureAsObjectV10 & ConfigurePresetsArchitectureAsObjectV1);
export type ConfigurePresetsToolsetV10 =
  | ConfigurePresetsToolsetAsStringV1
  | (ConfigurePresetsToolsetAsObjectV10 & ConfigurePresetsToolsetAsObjectV1);
export type ConfigurePresetsCacheVariablesAdditionalPropertiesV10 =
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsNullV1
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsBooleanV1
  | ConfigurePresetsCacheVariablesAdditionalPropertiesAsStringV1
  | (ConfigurePresetsCacheVariablesAdditionalPropertiesAsObjectV10 &
      ConfigurePresetsCacheVariablesAdditionalPropertiesAsObjectV1);
export type TopConditionV10 = ConditionV10 | TopConditionAsNullV3;
export type ConditionV10 =
  | ConditionAsBooleanV3
  | (ConditionAsObjectConstV10 & ConditionAsObjectConstV3)
  | (ConditionAsObjectEqualsV10 & ConditionAsObjectEqualsV3)
  | (ConditionAsObjectInListV10 & ConditionAsObjectInListV3)
  | (ConditionAsObjectMatchesV10 & ConditionAsObjectMatchesV3)
  | (ConditionAsObjectAggregationV10 & ConditionAsObjectAggregationV3)
  | (ConditionAsObjectNotV10 & ConditionAsObjectNotV3);
export type ConfigurePresetsV101 = {
  $comment?: unknown;
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  generator?: unknown;
  architecture?: ConfigurePresetsArchitectureV10;
  toolset?: ConfigurePresetsToolsetV10;
  toolchainFile?: unknown;
  graphviz?: unknown;
  binaryDir?: unknown;
  installDir?: unknown;
  cmakeExecutable?: unknown;
  cacheVariables?: {
    [k: string]: ConfigurePresetsCacheVariablesAdditionalPropertiesV10;
  };
  environment?: unknown;
  warnings?: {
    $comment?: unknown;
    dev?: unknown;
    deprecated?: unknown;
    uninitialized?: unknown;
    unusedCli?: unknown;
    systemVars?: unknown;
  };
  errors?: {
    $comment?: unknown;
    dev?: unknown;
    deprecated?: unknown;
  };
  debug?: {
    $comment?: unknown;
    output?: unknown;
    tryCompile?: unknown;
    find?: unknown;
  };
  condition?: TopConditionV10;
  trace?: {
    $comment?: unknown;
    mode?: unknown;
    format?: unknown;
    source?: unknown;
    redirect?: unknown;
  };
}[];
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 10 and higher.
 */
export type BuildPresetsV10 = BuildPresetsItemsV10 &
  BuildPresetsItemsV4 &
  BuildPresetsItemsV3 &
  BuildPresetsItemsV2 &
  BuildPresetsV101;
/**
 * An optional array of build preset objects. Used to specify arguments to cmake --build. Available in version 10 and higher.
 */
export type BuildPresetsItemsV10 = {
  $comment?: $Comment;
  [k: string]: unknown;
}[];
export type BuildPresetsV101 = {
  $comment?: unknown;
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  jobs?: unknown;
  targets?: unknown;
  configuration?: unknown;
  cleanFirst?: unknown;
  resolvePackageReferences?: unknown;
  verbose?: unknown;
  nativeToolOptions?: unknown;
  condition?: TopConditionV10;
}[];
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 10 and higher.
 */
export type TestPresetsV10 = TestPresetsItemsV10 &
  TestPresetsItemsV6 &
  TestPresetsItemsV5 &
  TestPresetsItemsV3 &
  TestPresetsItemsV2 &
  TestPresetsV101;
/**
 * An optional array of test preset objects. Used to specify arguments to ctest. Available in version 10 and higher.
 */
export type TestPresetsItemsV10 = {
  $comment?: $Comment;
  filter?: {
    $comment?: $Comment;
    include?: {
      $comment?: $Comment;
      [k: string]: unknown;
    };
    exclude?: {
      $comment?: $Comment;
      fixtures?: {
        $comment?: $Comment;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  execution?: {
    $comment?: $Comment;
    repeat?: {
      $comment?: $Comment;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type TestPresetsFilterIncludeIndexV10 =
  | TestPresetsFilterIncludeIndexAsStringV2
  | (TestPresetsFilterIncludeIndexAsObjectV10 & TestPresetsFilterIncludeIndexAsObjectV2);
export type TestPresetsV101 = {
  $comment?: unknown;
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  configuration?: unknown;
  overwriteConfigurationFile?: unknown;
  output?: {
    shortProgress?: unknown;
    verbosity?: unknown;
    debug?: unknown;
    outputOnFailure?: unknown;
    quiet?: unknown;
    outputLogFile?: unknown;
    outputJUnitFile?: unknown;
    labelSummary?: unknown;
    subprojectSummary?: unknown;
    maxPassedTestOutputSize?: unknown;
    maxFailedTestOutputSize?: unknown;
    maxTestNameWidth?: unknown;
    testOutputTruncation?: unknown;
  };
  filter?: {
    $comment?: unknown;
    include?: {
      $comment?: unknown;
      name?: unknown;
      label?: unknown;
      useUnion?: unknown;
      index?: TestPresetsFilterIncludeIndexV10;
    };
    exclude?: {
      $comment?: unknown;
      name?: unknown;
      label?: unknown;
      fixtures?: {
        $comment?: unknown;
        any?: unknown;
        setup?: unknown;
        cleanup?: unknown;
      };
    };
  };
  execution?: {
    $comment?: unknown;
    stopOnFailure?: unknown;
    enableFailover?: unknown;
    jobs?: unknown;
    resourceSpecFile?: unknown;
    testLoad?: unknown;
    showOnly?: unknown;
    repeat?: {
      $comment?: unknown;
      mode: unknown;
      count: unknown;
    };
    interactiveDebugging?: unknown;
    scheduleRandom?: unknown;
    timeout?: unknown;
    noTestsAction?: unknown;
  };
  condition?: TopConditionV10;
}[];
/**
 * An optional array of package preset objects. Used to specify arguments to cpack. Available in version 10 and higher.
 */
export type PackagePresetsV10 = PackagePresetsItemsV10 & PackagePresetsItemsV6 & PackagePresetsV101;
/**
 * An optional array of package preset objects. Used to specify arguments to cpack. Available in version 10 and higher.
 */
export type PackagePresetsItemsV10 = {
  $comment?: $Comment;
  output?: {
    $comment?: $Comment;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
export type PackagePresetsV101 = {
  $comment?: unknown;
  name: unknown;
  hidden?: unknown;
  inherits?: unknown;
  configurePreset?: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  inheritConfigureEnvironment?: unknown;
  environment?: unknown;
  condition?: TopConditionV10;
  generators?: unknown;
  configurations?: unknown;
  variables?: unknown;
  configFile?: unknown;
  output?: {
    $comment?: unknown;
    debug?: unknown;
    verbose?: unknown;
  };
  packageName?: unknown;
  packageVersion?: unknown;
  packageDirectory?: unknown;
  vendorName?: unknown;
}[];
/**
 * An optional array of workflow preset objects. Used to execute configure, build, test, and package presets in order. Available in version 10 and higher.
 */
export type WorkflowPresetsV10 = WorkflowPresetsItemsV10 & WorkflowPresetsItemsV6 & WorkflowPresetsV101;
/**
 * An optional array of workflow preset objects. Used to execute configure, build, test, and package presets in order. Available in version 10 and higher.
 */
export type WorkflowPresetsItemsV10 = {
  $comment?: $Comment;
  steps?: {
    $comment?: $Comment;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}[];
export type WorkflowPresetsV101 = {
  $comment?: unknown;
  name: unknown;
  vendor?: unknown;
  displayName?: unknown;
  description?: unknown;
  steps: {
    $comment?: unknown;
    type: unknown;
    name: unknown;
  }[];
}[];

/**
 * An optional object representing the minimum version of CMake needed to build this project. Available in version 1 and higher.
 */
export interface CmakeMinimumRequiredPropertiesV1 {
  /**
   * An optional integer representing the major version.
   */
  major?: number;
  /**
   * An optional integer representing the minor version.
   */
  minor?: number;
  /**
   * An optional integer representing the patch version.
   */
  patch?: number;
  [k: string]: unknown;
}
/**
 * An optional map containing vendor-specific information. CMake does not interpret the contents of this field except to verify that it is a map if it does exist. However, the keys should be a vendor-specific domain name followed by a /-separated path. For example, the Example IDE 1.0 could use example.com/ExampleIDE/1.0. The value of each field can be anything desired by the vendor, though will typically be a map.
 */
export interface Vendor {
  [k: string]: unknown;
}
/**
 * An optional object representing the platform for generators that support it. Available in version 1 and higher.
 */
export interface ConfigurePresetsArchitectureAsObjectV1 {
  /**
   * An optional string representing the value.
   */
  value?: string;
  /**
   * An optional string telling CMake how to handle the field. Valid values are: "set" Set the respective value. This will result in an error for generators that do not support the respective field. "external" Do not set the value, even if the generator supports it. This is useful if, for example, a preset uses the Ninja generator, and an IDE knows how to set up the Visual C++ environment from the architecture and toolset fields. In that case, CMake will ignore the field, but the IDE can use them to set up the environment before invoking CMake.
   */
  strategy?: "set" | "external";
  [k: string]: unknown;
}
/**
 * An optional object representing the toolset for generators that support it. Available in version 1 and higher.
 */
export interface ConfigurePresetsToolsetAsObjectV1 {
  /**
   * An optional string representing the value.
   */
  value?: string;
  /**
   * An optional string telling CMake how to handle the field. Valid values are: "set" Set the respective value. This will result in an error for generators that do not support the respective field. "external" Do not set the value, even if the generator supports it. This is useful if, for example, a preset uses the Ninja generator, and an IDE knows how to set up the Visual C++ environment from the architecture and toolset fields. In that case, CMake will ignore the field, but the IDE can use them to set up the environment before invoking CMake.
   */
  strategy?: "set" | "external";
  [k: string]: unknown;
}
/**
 * An optional object representing the cache variables for generators that support it. Available in version 1 and higher.
 */
export interface ConfigurePresetsCacheVariablesAdditionalPropertiesAsObjectV1 {
  /**
   * An optional string representing the type of the variable. It should be BOOL, FILEPATH, PATH, STRING, or INTERNAL.
   */
  type?: string;
  value?: boolean | string;
  [k: string]: unknown;
}
/**
 * An optional object specifying tests to include by test index. Available in version 2 and higher.
 */
export interface TestPresetsFilterIncludeIndexAsObjectV2 {
  /**
   * An optional integer specifying a test index to start testing at.
   */
  start?: number;
  /**
   * An optional integer specifying a test index to stop testing at.
   */
  end?: number;
  /**
   * An optional integer specifying the increment.
   */
  stride?: number;
  /**
   * An optional array of integers specifying specific test indices to run.
   */
  specificTests?: number[];
  [k: string]: unknown;
}
export interface ConditionAsObjectConstV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "const";
  /**
   * A required boolean which provides a constant value for the condition's evaluation.
   */
  value?: boolean;
  [k: string]: unknown;
}
export interface ConditionAsObjectEqualsV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "equals" | "notEquals";
  /**
   * First string to compare. This field supports macro expansion.
   */
  lhs?: string;
  /**
   * Second string to compare. This field supports macro expansion.
   */
  rhs?: string;
  [k: string]: unknown;
}
export interface ConditionAsObjectInListV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "inList" | "notInList";
  /**
   * A required string to search for. This field supports macro expansion.
   */
  string?: string;
  /**
   * A required list of strings to search. This field supports macro expansion, and uses short-circuit evaluation.
   */
  list?: string[];
  [k: string]: unknown;
}
export interface ConditionAsObjectMatchesV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "matches" | "notMatches";
  /**
   * A required string to search. This field supports macro expansion.
   */
  string?: string;
  /**
   * A required regular expression to search for. This field supports macro expansion.
   */
  regex?: string;
  [k: string]: unknown;
}
export interface ConditionAsObjectAggregationV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "anyOf" | "allOf";
  /**
   * A required array of condition objects. These conditions use short-circuit evaluation.
   */
  conditions?: unknown[];
  [k: string]: unknown;
}
export interface ConditionAsObjectNotV3 {
  /**
   * A required string specifying the type of the condition.
   */
  type?: "not";
  [k: string]: unknown;
}
/**
 * An optional object representing the minimum version of CMake needed to build this project. Available in version 10 and higher.
 */
export interface CmakeMinimumRequiredPropertiesV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
/**
 * An optional object representing the platform for generators that support it. Available in version 10 and higher.
 */
export interface ConfigurePresetsArchitectureAsObjectV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
/**
 * An optional object representing the toolset for generators that support it. Available in version 10 and higher.
 */
export interface ConfigurePresetsToolsetAsObjectV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
/**
 * An optional object representing the cache variables for generators that support it. Available in version 10 and higher.
 */
export interface ConfigurePresetsCacheVariablesAdditionalPropertiesAsObjectV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectConstV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectEqualsV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectInListV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectMatchesV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectAggregationV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
export interface ConditionAsObjectNotV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
/**
 * An optional object specifying tests to include by test index. Available in version 10 and higher.
 */
export interface TestPresetsFilterIncludeIndexAsObjectV10 {
  $comment?: $Comment;
  [k: string]: unknown;
}
