#ifndef XENOPHYTECENTRALIZEDALGORITHM_H
#define XENOPHYTECENTRALIZEDALGORITHM_H

#include "global.h"

DOTNET_PUBLIC void XenophyteCentralizedAlgorithm_GenerateCertificate(DOTNET_STRING header, DOTNET_INT keySize, DOTNET_SPAN_BYTE output);
DOTNET_PUBLIC DOTNET_INT XenophyteCentralizedAlgorithm_GenerateEasyBlockNumbers(DOTNET_LONG minValue, DOTNET_LONG maxValue, DOTNET_SPAN_LONG output);
DOTNET_PUBLIC DOTNET_INT XenophyteCentralizedAlgorithm_GenerateNonEasyBlockNumbers(DOTNET_LONG minValue, DOTNET_LONG maxValue, DOTNET_READ_ONLY_SPAN_LONG easyBlockValues, DOTNET_INT easyBlockValuesLength, DOTNET_SPAN_LONG output);
DOTNET_PUBLIC DOTNET_BOOL XenophyteCentralizedAlgorithm_MakeEncryptedShare(DOTNET_READ_ONLY_SPAN_BYTE input, DOTNET_INT inputLength, DOTNET_SPAN_BYTE encryptedShare, DOTNET_SPAN_BYTE hashEncryptedShare, DOTNET_READ_ONLY_SPAN_BYTE xorKey, DOTNET_INT xorKeyLength, DOTNET_INT aesKeySize, DOTNET_READ_ONLY_SPAN_BYTE aesKey, DOTNET_READ_ONLY_SPAN_BYTE aesIv, DOTNET_INT aesRound);

#endif
