#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define PROJECT_NAME "Xenorig"
#define PROJECT_SITE "https://github.com/TheDialgaTeam/Xenorig"

#define COMPILER_ID "MSVC"
#define COMPILER_VERSION "19.42.34435.0"

#define APP_VER_MAJOR 2
#define APP_VER_MINOR 0
#define APP_VER_REV 0
#define APP_VER_BUILD 0

#define BUILD_COMMIT_ID "91e45e1"
#define PROJECT_VERSION STR(APP_VER_MAJOR) "." STR(APP_VER_MINOR) "." STR(APP_VER_REV) "." STR(APP_VER_BUILD)
#define PROJECT_VERSION_LONG PROJECT_VERSION " (" BUILD_COMMIT_ID ")"
#define PROJECT_DESCRIPTION PROJECT_NAME " " PROJECT_VERSION_LONG
