// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xenopool.Server.Database;

#nullable disable

namespace Xenopool.Server.Migrations
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20230423084443_1.0.0")]
    partial class _100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Xenopool.Server.Database.Tables.PoolAccount", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MinimumPayoutAmount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PayoutAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("WalletAddress");

                    b.ToTable("PoolAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
