name: Build and Deploy Xenorig

on:
  push:
    tags:
      - v*

env:
  XENORIG_CSPROJ_FILE: "Xenorig/Xenorig.csproj"
  XENORIG_PUBLISH_ROOT: "Xenorig/publish"

  XENORIG_NATIVE_SOURCE_ROOT: "XenoLibNative"
  XENORIG_NATIVE_BUILD_ROOT: "XenoLibNative/build"
  XENORIG_NATIVE_INSTALL_ROOT: "XenoLibNative/build/install"
  XENORIG_NATIVE_VCPKG_ROOT: "XenoLibNative/vcpkg"

  TEMP_DIRECTORY: "temp"
  DOTNET_PATH: "temp/dotnet"
  DOTNET_VERSION: "6.0"
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  VCPKG_NUGET_REPOSITORY: "https://github.com/${{ github.repository }}"
  VCPKG_BINARY_SOURCES: clear;nuget,github/${{ github.repository_owner }},readwrite

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_Xenorig:
    name: Build Xenorig (${{ matrix.output_folder }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]
        arch: [x64, x86, arm, arm64]
        exclude:
          - os: windows-2022
            arch: arm
          - os: windows-2022
            arch: arm64
          - os: ubuntu-20.04
            arch: x86
          - os: macos-11
            arch: x86
          - os: macos-11
            arch: arm
          - os: macos-11
            arch: arm64
        include:
          - os: windows-2022
            arch: x64
            install: ""
            post_install: []
            output_folder: Xenorig-windows-x64
            Xenorig_native:
              cmake_generator: ninja
              cmake_build_type: Release
              cmake_target_triplet: x64-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: CLANG64
              msys2_install: >-
                mingw-w64-clang-x86_64-toolchain
                mingw-w64-clang-x86_64-cmake
                mingw-w64-clang-x86_64-ninja
              cc: "clang"
              cxx: "clang++"
            Xenorig:
              configuration: Release
              arch: win-x64
              target_framework: net6.0

          - os: windows-2022
            arch: x86
            install: ""
            post_install: []
            output_folder: Xenorig-windows-x86
            Xenorig_native:
              cmake_generator: ninja
              cmake_build_type: Release
              cmake_target_triplet: x86-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: CLANG32
              msys2_install: >-
                mingw-w64-clang-i686-toolchain
                mingw-w64-clang-i686-cmake
                mingw-w64-clang-i686-ninja
              cc: "clang"
              cxx: "clang++"
            Xenorig:
              configuration: Release
              arch: win-x86
              target_framework: net6.0

          - os: ubuntu-20.04
            arch: x64
            install: >-
              clang
              cmake
            post_install: []
            output_folder: Xenorig-linux-x64
            Xenorig_native:
              cmake_generator: Unix Makefiles
              cmake_build_type: Release
              cmake_target_triplet: x64-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: ""
              msys2_install: ""
              cc: clang
              cxx: clang++
            Xenorig:
              configuration: Release
              arch: linux-x64
              target_framework: net6.0

          - os: ubuntu-20.04
            arch: arm
            install: >-
              clang
              cmake
              binutils-arm-linux-gnueabihf
              libc6-dev-armhf-cross
              libstdc++-9-dev-armhf-cross
            post_install: []
            output_folder: Xenorig-linux-arm
            Xenorig_native:
              cmake_generator: Unix Makefiles
              cmake_build_type: Release
              cmake_target_triplet: arm-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: ""
              msys2_install: ""
              cc: clang
              cxx: clang++
            Xenorig:
              configuration: Release
              arch: linux-arm
              target_framework: net6.0

          - os: ubuntu-20.04
            arch: arm64
            install: >-
              clang
              cmake
              binutils-aarch64-linux-gnu
              libc6-dev-arm64-cross
              libstdc++-9-dev-arm64-cross
            post_install: []
            output_folder: Xenorig-linux-arm64
            Xenorig_native:
              cmake_generator: Unix Makefiles
              cmake_build_type: Release
              cmake_target_triplet: arm64-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: ""
              msys2_install: ""
              cc: clang
              cxx: clang++
            Xenorig:
              configuration: Release
              arch: linux-arm64
              target_framework: net6.0

          - os: macos-11
            arch: x64
            install: >-
              llvm
              cmake
            post_install: []
            output_folder: Xenorig-osx-x64
            Xenorig_native:
              cmake_generator: Unix Makefiles
              cmake_build_type: Release
              cmake_target_triplet: x64-clang-static-release
              cmake_toolchain_file: ""
              msys2_environment: ""
              msys2_install: ""
              cc: clang
              cxx: clang++
            Xenorig:
              configuration: Release
              arch: osx-x64
              target_framework: net6.0

    steps:
      # Init
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: ${{ github.workspace }}/${{ env.XENORIG_NATIVE_VCPKG_ROOT }}
          appendedCacheKey: ${{ matrix.output_folder }}

      - name: Setup NuGet Credentials
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github/${{ github.repository_owner }}" --username "${{ github.actor }}" --password "${{ github.token }}" --store-password-in-clear-text
          
          if ("${env:RUNNER_OS}" -ne 'Windows')
          {
            $vcpkg_executable = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_NATIVE_VCPKG_ROOT}" 'vcpkg'

            $nuget_executable = @(Invoke-Expression "$vcpkg_executable fetch nuget") | Select-Object -Last 1
            Invoke-Expression "mono $nuget_executable sources add -source `"https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json`" -name `"github/${{ github.repository_owner }}`" -username `"${{ github.actor }}`" -password `"${{ github.token }}`" -storepasswordincleartext"
          }

      # Install
      - name: Install Program / Dependencies
        env:
          INSTALL: ${{ matrix.install }}
          POST_INSTALL: ${{ join(matrix.post_install, ' && ') }}
        run: |
          if ("${env:RUNNER_OS}" -eq 'Windows')
          {
            if (![string]::IsNullOrWhiteSpace("${env:INSTALL}"))
            {
              Invoke-Expression "choco install ${env:INSTALL} -y"
            }
            
            if (![string]::IsNullOrWhiteSpace("${env:POST_INSTALL}"))
            {
              Invoke-Expression "${env:POST_INSTALL}"
            }
          }
          elseif ("${env:RUNNER_OS}" -eq 'Linux')
          {
            if (![string]::IsNullOrWhiteSpace("${env:INSTALL}"))
            {
              sudo apt-get update -y
              Invoke-Expression "sudo apt-get install ${env:INSTALL} -y"
            }
            
            if (![string]::IsNullOrWhiteSpace("${env:POST_INSTALL}"))
            {
              Invoke-Expression "${env:POST_INSTALL}"
            }
          }
          elseif ("${env:RUNNER_OS}" -eq 'macOS')
          {
            if (![string]::IsNullOrWhiteSpace("${env:INSTALL}"))
            {
              brew update
              Invoke-Expression "brew install ${env:INSTALL}"
            }
            
            if (![string]::IsNullOrWhiteSpace("${env:POST_INSTALL}"))
            {
              Invoke-Expression "${env:POST_INSTALL}"
            }
          }
          
      - name: Install dotnet
        run: |
          $temp_directory = Join-Path "${env:GITHUB_WORKSPACE}" "${env:TEMP_DIRECTORY}"
          New-Item "$temp_directory" -ItemType 'Directory' -Force

          if ("${env:RUNNER_OS}" -eq 'Windows')
          {
            $dotnet_install_script_file_path = Join-Path "$temp_directory" 'dotnet-install.ps1'
            $dotnet_install_directory = Join-Path "${env:GITHUB_WORKSPACE}" "${env:DOTNET_PATH}"

            Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "$dotnet_install_script_file_path"
            Invoke-Expression "$dotnet_install_script_file_path -Channel `"${env:DOTNET_VERSION}`" -InstallDir `"$dotnet_install_directory`""
          }
          else
          {
            $dotnet_install_script_file_path = Join-Path "$temp_directory" 'dotnet-install.sh'
            $dotnet_install_directory = Join-Path "${env:GITHUB_WORKSPACE}" "${env:DOTNET_PATH}"

            Invoke-WebRequest "https://dot.net/v1/dotnet-install.sh" -OutFile "$dotnet_install_script_file_path"
            /usr/bin/env bash -c "chmod u+x $dotnet_install_script_file_path && $dotnet_install_script_file_path -Channel `"${env:DOTNET_VERSION}`" -InstallDir `"$dotnet_install_directory`""
          }

      - name: Setup msys2 environemnt
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          update: true
          install: ${{ matrix.Xenorig_native.msys2_install }}

      # Build Xenorig Native
      - name: Build Xenorig Native
        env:
          XENORIG_NATIVE_CMAKE_GENERATOR: ${{ matrix.Xenorig_native.cmake_generator }}
          XENORIG_NATIVE_CMAKE_BUILD_TYPE: ${{ matrix.Xenorig_native.cmake_build_type }}
          XENORIG_NATIVE_CMAKE_TARGET_TRIPLET: ${{ matrix.Xenorig_native.cmake_target_triplet }}
          XENORIG_NATIVE_CMAKE_TOOLCHAIN_FILE: ${{ matrix.Xenorig_native.cmake_toolchain_file }}
          XENORIG_NATIVE_USE_MSYS2: ${{ matrix.Xenorig_native.use_msys2 }}
          XENORIG_NATIVE_MSYS2_ENVIRONMENT: ${{ matrix.Xenorig_native.msys2_environment }}
          XENORIG_NATIVE_CC: ${{ matrix.Xenorig_native.cc }}
          XENORIG_NATIVE_CXX: ${{ matrix.Xenorig_native.cxx }}
        run: |
          $cmake_generator = "${env:XENORIG_NATIVE_CMAKE_GENERATOR}"

          $cmake_build_type = "${env:XENORIG_NATIVE_CMAKE_BUILD_TYPE}"
          $cmake_target_triplet = "${env:XENORIG_NATIVE_CMAKE_TARGET_TRIPLET}"
          $cmake_toolchain_file = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_NATIVE_SOURCE_ROOT}" 'cmake' "${env:XENORIG_NATIVE_CMAKE_TOOLCHAIN_FILE}"

          $cmake_source_root = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_NATIVE_SOURCE_ROOT}"
          $cmake_build_root = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_NATIVE_BUILD_ROOT}"
          $cmake_install_prefix = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_NATIVE_INSTALL_ROOT}"

          $custom_triplets_root = Join-Path "$cmake_source_root" "triplets"

          $env:CC = "${env:XENORIG_NATIVE_CC}"
          $env:CXX = "${env:XENORIG_NATIVE_CXX}"
          $env:VCPKG_OVERLAY_TRIPLETS = "$custom_triplets_root"

          if ("${env:RUNNER_OS}" -eq 'Windows')
          {
            $cmake_source_root = $cmake_source_root.Replace('\', '/')
            $cmake_build_root = $cmake_build_root.Replace('\', '/')
            $cmake_install_prefix = $cmake_install_prefix.Replace('\', '/')

            $env:MSYSTEM = "${env:XENORIG_NATIVE_MSYS2_ENVIRONMENT}"

            msys2 -c "cmake -G \`"$cmake_generator\`" -DCMAKE_BUILD_TYPE=\`"$cmake_build_type\`" -DVCPKG_TARGET_TRIPLET=\`"$cmake_target_triplet\`" -DCMAKE_INSTALL_PREFIX=\`"$cmake_install_prefix\`" -S \`"$cmake_source_root\`" -B \`"$cmake_build_root\`""
            msys2 -c "cd \`"$cmake_build_root\`" && cmake --build . && cmake --install ."
          }
          else
          {
            if (![string]::IsNullOrWhiteSpace("${env:XENORIG_NATIVE_CMAKE_TOOLCHAIN_FILE}"))
            {
              cmake -G "$cmake_generator" -DCMAKE_BUILD_TYPE="$cmake_build_type" -DVCPKG_TARGET_TRIPLET="$cmake_target_triplet" -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="$cmake_toolchain_file" -DCMAKE_INSTALL_PREFIX="$cmake_install_prefix" -S "$cmake_source_root" -B "$cmake_build_root"
            }
            else
            {
              cmake -G "$cmake_generator" -DCMAKE_BUILD_TYPE="$cmake_build_type" -DVCPKG_TARGET_TRIPLET="$cmake_target_triplet" -DCMAKE_INSTALL_PREFIX="$cmake_install_prefix" -S "$cmake_source_root" -B "$cmake_build_root"
            }

            cd "$cmake_build_root"
            cmake --build .
            cmake --install .
          }

      # Build Xenorig
      - name: Patch Xenorig csproj
        env:
          XENORIG_TARGET_FRAMEWORK: ${{ matrix.Xenorig.target_framework }}
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $version = (${env:GITHUB_REF} -split "/" | Select-Object -Last 1).Replace('v', '')
          $csproj_file = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_CSPROJ_FILE}"
          ((Get-Content "$csproj_file") -replace '^(\s*)<Version>.+?<\/Version>(\s*)$', "`$1<Version>$version</Version>`$2") | Set-Content "$csproj_file"
          ((Get-Content "$csproj_file") -replace '^(\s*)<TargetFramework>.+?<\/TargetFramework>(\s*)$', "`$1<TargetFramework>${env:XENORIG_TARGET_FRAMEWORK}</TargetFramework>`$2") | Set-Content "$csproj_file"

      - name: Build Xenorig
        env:
          XENORIG_OUTPUT_FOLDER: ${{ matrix.output_folder }}
          XENORIG_CONFIGURATION: ${{ matrix.Xenorig.configuration }}
          XENORIG_ARCH: ${{ matrix.Xenorig.arch }}
        run: |
          $dotnet = Join-Path "${env:GITHUB_WORKSPACE}" "${env:DOTNET_PATH}" 'dotnet'
          $output = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_PUBLISH_ROOT}" "${env:XENORIG_OUTPUT_FOLDER}"
          Invoke-Expression "$dotnet publish -c ${env:XENORIG_CONFIGURATION} --runtime ${env:XENORIG_ARCH} -o `"$output`" --self-contained -p:PublishTrimmed=true -p:PublishReadyToRun=true"

      # Package
      - name: Package Xenorig
        env:
          XENORIG_OUTPUT_FOLDER: ${{ matrix.output_folder }}
        run: |
          $Xenorig_publish_root = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_PUBLISH_ROOT}"
          Set-Location "$Xenorig_publish_root"

          if ("${env:RUNNER_OS}" -eq 'Windows')
          {
            Invoke-Expression "7z a `"${env:XENORIG_OUTPUT_FOLDER}.zip`" `"${env:XENORIG_OUTPUT_FOLDER}`" -mx=9"
          }
          else
          {
            Invoke-Expression "7z a `"${env:XENORIG_OUTPUT_FOLDER}.tar`" `"${env:XENORIG_OUTPUT_FOLDER}`""
            Invoke-Expression "7z a `"${env:XENORIG_OUTPUT_FOLDER}.tar.gz`" `"${env:XENORIG_OUTPUT_FOLDER}.tar`" -mx=9"
          }

      # Upload Artifacts
      - name: Upload Xenorig artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output_folder }}
          path: |
            ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}/*.*
            !${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}/*.tar

  deploy_Xenorig:
    name: Deploy Xenorig
    runs-on: ubuntu-20.04
    needs: [build_Xenorig]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Init
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Xenorig artifact directory
        run: |
          $Xenorig_native_install_root = Join-Path "${env:GITHUB_WORKSPACE}" "${env:XENORIG_PUBLISH_ROOT}"
          New-Item "$Xenorig_native_install_root" -ItemType 'Directory' -Force

      - name: Download Xenorig artifact (windows-x64)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-windows-x64
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      - name: Download Xenorig artifact (windows-x86)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-windows-x86
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      - name: Download Xenorig artifact (linux-x64)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-linux-x64
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      - name: Download Xenorig artifact (linux-arm)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-linux-arm
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      - name: Download Xenorig artifact (linux-arm64)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-linux-arm64
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      - name: Download Xenorig artifact (osx-x64)
        uses: actions/download-artifact@v2
        with:
          name: Xenorig-osx-x64
          path: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}

      # Deploy
      - name: Get version number
        id: get_version
        run: |
          $version = "${env:GITHUB_REF}" -split '/' | Select-Object -Last 1
          Write-Output "::set-output name=version::$version"

      - name: Deploy Xenorig
        uses: softprops/action-gh-release@v1
        with:
          name: Xenorig ${{ steps.get_version.outputs.version }}
          body_path: ${{ github.workspace }}/RELEASE_TEMPLATE.md
          files: ${{ github.workspace }}/${{ env.XENORIG_PUBLISH_ROOT }}/*
          draft: true
          fail_on_unmatched_files: true
